# ---------------------------------------------------------------
# NTRIP client configuration
# ---------------------------------------------------------------
# Set hostname, mountpoint, username, and password to match your
# NTRIP caster subscription.
# ---------------------------------------------------------------

calian_gnss:
  ntrip_client:
    ros__parameters:
      hostname: "<YOUR_NTRIP_HOST>"
      port: 2101
      mountpoint: "<YOUR_MOUNTPOINT>"
      username: "<YOUR_USERNAME>"
      password: "<YOUR_PASSWORD>"
